spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/Finance/protocol/openid-connect/certs

scheduler:
  create:
    bill:
      fixed-rate: 60000
      initial-delay: 60000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method