spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintrack
    username: postgres
    password: postgres
  jpa:
    show-sql: false
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/fintrack/protocol/openid-connect/certs

scheduler:
  create:
    bill:
      fixed-rate: 60000
      initial-delay: 60000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

security:
  cors:
    allowedOrigins: http://localhost:4200
    allowedMethods: GET,POST,PUT,DELETE
    allowedHeaders: "*"