spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintrack
    username: postgres
    password: postgres
  jpa:
    show-sql: false
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso

scheduler:
  create:
    bill:
      fixed-rate: 60000
      initial-delay: 60000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

security:
  cors:
    allowedOrigins: http://localhost:4200
    allowedMethods: GET,POST,PUT,DELETE
    allowedHeaders: "*"
  token:
    secret-key: my-secret-key
    expiration-time-in-minutes: 60