name: Generate Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build App
      run: mvn -B package --file pom.xml
    - name: Build and Push Docker Image
      run: mvn jib:build -Djib.to.auth.username=${{secrets.DOCKERHUB_USERNAME}} -Djib.to.auth.password=${{secrets.DOCKERHUB_PASSWORD}}
